name: CICD Pipeline

on:
  push:
    branches:
      - '**'
  workflow_dispatch:
    inputs:
      stage:
        description: "Select promotion stage"
        required: true
        type: choice
        options:
          - test
          - prod

env:
  IMAGE_NAME_BFF: ${{ secrets.DOCKER_USERNAME }}/nexora-bff
  IMAGE_NAME_MQTT_HANDLER: ${{ secrets.DOCKER_USERNAME }}/nexora-mqtt-handler

jobs:

  #  # 1️⃣ LINT
  #  lint:
  #    runs-on: ubuntu-latest
  #    steps:
  #      - uses: actions/checkout@v4
  #      - run: npm install
  #      - run: npm run lint:check
  #
  #  # 2️⃣ TEST
  #  test:
  #    runs-on: ubuntu-latest
  #    steps:
  #      - uses: actions/checkout@v4
  #      - run: npm install
  #      - run: npm test:coverage

  # 3️⃣ BUILD ARTIFACT
  build-bff:
    #    needs: [lint, test]
    runs-on: ubuntu-latest

    outputs:
      sha: ${{ steps.meta.outputs.sha }}

    steps:
      - uses: actions/checkout@v4

      - name: Set SHA
        id: meta
        run: echo "sha=${GITHUB_SHA::7}" >> $GITHUB_OUTPUT

      - uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: npm
      - run: |
          npm ci --no-audit --no-fund
          npm run build

      - uses: docker/setup-qemu-action@v3
      - uses: docker/setup-buildx-action@v3

      - name: Login
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      # Optimized multi-arch build with GitHub cache
      - name: Build & Push (Multi-Arch + Cache)
        uses: docker/build-push-action@v5
        with:
          context: .
          platforms: linux/arm64,linux/amd64
          file: ./dockerfile/bff.Dockerfile
          push: true
          tags: ${{ env.IMAGE_NAME_BFF }}:${{ steps.meta.outputs.sha }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

  # 4️⃣ AUTO DEPLOY DEV (if develop branch)
  dev-bff:
    needs: build-bff
    runs-on: ubuntu-latest

    steps:
      - name: Login
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Promote → DEV
        run: |
          docker buildx imagetools create \
          -t $IMAGE_NAME_BFF:dev \
          $IMAGE_NAME_BFF:${{ needs.build.outputs.sha }}

  test-bff:
    needs: [dev-bff, build-bff]
    if: github.event_name == 'workflow_dispatch' && (github.event.inputs.stage == 'test' || github.event.inputs.stage == 'prod')
    runs-on: ubuntu-latest

    steps:
      - name: Login
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Promote → TEST
        run: |
          docker buildx imagetools create \
            -t $IMAGE_NAME_BFF:test \
            $IMAGE_NAME_BFF:${{ needs.build.outputs.sha }}

  prod-bff:
    needs: [test-bff, build-bff]
    if: github.event_name == 'workflow_dispatch' && github.event.inputs.stage == 'prod'
    runs-on: ubuntu-latest

    steps:
      - name: Login
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Promote → PROD
        run: |
          docker buildx imagetools create \
            -t $IMAGE_NAME_BFF:prod \
            $IMAGE_NAME_BFF:${{ needs.build.outputs.sha }}
          

  #  # 1️⃣ LINT
  #  lint:
  #    runs-on: ubuntu-latest
  #    steps:
  #      - uses: actions/checkout@v4
  #      - run: npm install
  #      - run: npm run lint:check
  #
  #  # 2️⃣ TEST
  #  test:
  #    runs-on: ubuntu-latest
  #    steps:
  #      - uses: actions/checkout@v4
  #      - run: npm install
  #      - run: npm test:coverage

  # 3️⃣ BUILD ARTIFACT
  build-mqtt-handler:
    #    needs: [lint, test]
    runs-on: ubuntu-latest

    outputs:
      sha: ${{ steps.meta.outputs.sha }}

    steps:
      - uses: actions/checkout@v4

      - name: Set SHA
        id: meta
        run: echo "sha=${GITHUB_SHA::7}" >> $GITHUB_OUTPUT

      - uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: npm
      - run: |
          npm ci --no-audit --no-fund
          npm run build

      - uses: docker/setup-qemu-action@v3
      - uses: docker/setup-buildx-action@v3

      - name: Login
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      # Optimized multi-arch build with GitHub cache
      - name: Build & Push (Multi-Arch + Cache)
        uses: docker/build-push-action@v5
        with:
          context: .
          platforms: linux/arm64,linux/amd64
          file: ./dockerfile/mqtt-handler.Dockerfile
          push: true
          tags: ${{ env.IMAGE_NAME_MQTT_HANDLER }}:${{ steps.meta.outputs.sha }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

  # 4️⃣ AUTO DEPLOY DEV (if develop branch)
  dev-mqtt-handler:
    needs: build-mqtt-handler
    runs-on: ubuntu-latest

    steps:
      - name: Login
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Promote → DEV
        run: |
          docker buildx imagetools create \
          -t $IMAGE_NAME_MQTT_HANDLER:dev \
          $IMAGE_NAME_MQTT_HANDLER:${{ needs.build.outputs.sha }}

  test-mqtt-handler:
    needs: [dev-mqtt-handler, build-mqtt-handler]
    if: github.event_name == 'workflow_dispatch' && (github.event.inputs.stage == 'test' || github.event.inputs.stage == 'prod')
    runs-on: ubuntu-latest

    steps:
      - name: Login
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Promote → TEST
        run: |
          docker buildx imagetools create \
            -t $IMAGE_NAME_MQTT_HANDLER:test \
            $IMAGE_NAME_MQTT_HANDLER:${{ needs.build.outputs.sha }}

  prod-mqtt-handler:
    needs: [test-mqtt-handler, build-mqtt-handler]
    if: github.event_name == 'workflow_dispatch' && github.event.inputs.stage == 'prod'
    runs-on: ubuntu-latest

    steps:
      - name: Login
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Promote → PROD
        run: |
          docker buildx imagetools create \
            -t $IMAGE_NAME_MQTT_HANDLER:prod \
            $IMAGE_NAME_MQTT_HANDLER:${{ needs.build.outputs.sha }}